commerce_payment.commerce_payment_gateway.plugin.vipps:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    merchant_serial_number:
      type: string
      label: 'Merchant Serial Number'
    token:
      type: string
      label: 'Token'
